export const optionsWilayah:any[]=[    
    {kw:1,label:'Molosipat'},
    {kw:2,label:'Buladu'},
    {kw:3,label:'Pilolodaa'},
    {kw:4,label:'Lekobalo'},
    {kw:5,label:'Dembe'},
    {kw:6,label:'Iluta'},
    
    {kw:7,label:'Bua'},
    {kw:8,label:'Huntu'},
    {kw:9,label:'Payunga'},
    {kw:10,label:'Tabongo Timur'},
    {kw:11,label:'Tabongo Barat'},
    {kw:12,label:'Limehe Timur'},
    {kw:13,label:'Limehe Barat'},
    {kw:14,label:'Sombari'},
    {kw:15,label:'Bongomeme'},
    {kw:16,label:'Isimu'},
    {kw:17,label:'Buhu'},
    {kw:18,label:'Labanu'},
    {kw:19,label:'Pontolo'},
    {kw:20,label:'Molinggapoto'},
    
    {kw:21,label:'Titidu'},
    {kw:22,label:'Bulalo'},
    {kw:23,label:'Moluo'},
    {kw:24,label:'Gentuma'},
    {kw:25,label:'Antinggola'},
    {kw:26,label:'Pinogaluman'},
    {kw:27,label:'Buko'},
    {kw:28,label:'Boroko'},
    {kw:29,label:'Sangkub'},
    {kw:30,label:'Lolak'},
    {kw:31,label:'Poigar'},
    {kw:32,label:'Amurang'},
    {kw:33,label:'Malalayang'},
    {kw:34,label:'Manado'},
    
    {kw:35,label:'Kalimat yang panjang digunakan untuk wrapper bagaimana model tampilan'},          
];